### ISSUE TITLE
Add seqr to available software

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/compare_blast#2]
seqr passed that original test [here](https://gist.github.com/necrolyte2/baf578c2e922de74b65a) so I will add it into the Makefile.
Right now I'm building it with leiningen but I'll try to make sure you can build it with maven or I'll just supply a jar. It'll have to clone the solr configuration but that comes in the repo so that should be simple. No need to install solr

**Comment by necrolyte2** [comment]
awesome! I'm still trying to figure out how to really produce the test results that are easily viewable.

Will then work on getting tests to span nodes as well

**Comment by averagehat** [comment]
closed by #4
